*-----------------------------------------------------------
* Title      :  Pratical 4
* Written by :  Rachel O Shea
* Date       :  04/02/2026
* Description:  Practical 4 Task 4
*-----------------------------------------------------------
    ORG    $1000
START:                  ; first instruction of program



    SIMHALT             ; halt simulator

* Put variables and constants here

    END    START        ; last line of source

*~Font name~Courier New~
*~Font size~10~
*~Tab type~1~
*~Tab size~4~
